# syntax=docker/dockerfile:1.7

FROM maven:3.9.9-eclipse-temurin-21
WORKDIR /workspace

COPY .mvn .mvn
COPY mvnw pom.xml ./
RUN chmod +x mvnw && ./mvnw -q -DskipTests dependency:go-offline

COPY src src
EXPOSE 8080
CMD ["./mvnw", "spring-boot:run"]
