spring.application.name=jobhunter-be

server.port=${PORT:8080}

# PostgreSQL DB config
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT config
jwt.base64-secret=U29tZVZlcnlMb25nU2VjcmV0S2V5Rm9yU2lnbmluZ0pXVHdpdGg1MTI=
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=2592000000

#WS config
websocket.allowed-origins=${WEBSOCKET_ALLOWED_ORIGINS:http://localhost:3000,http://127.0.0.1:3000}

# Actuator / Health Probes (for Railway health checks)
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
