spring.application.name=jobhunter-be
server.port=${PORT:8080}

# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/jobhunter
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT config
jwt.base64-secret=U29tZVZlcnlMb25nU2VjcmV0S2V5Rm9yU2lnbmluZ0pXVHdpdGg1MTI=
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=2592000000

# WebSocket config
websocket.allowed-origins=${WEBSOCKET_ALLOWED_ORIGINS:https://summer-project-fe.vercel.app}

# Actuator / Health Probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true

# DevTools / Hot Reload
spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true
spring.devtools.restart.additional-paths=src/main/java
spring.devtools.restart.exclude=static/**,public/**
